config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # get 'index', to: 'application#index'

  resources :authors

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books, dependent: :destroy
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

# def index
#     @authors = Author.all  
# end

end

app/controllers/authors_controller.rb
class AuthorsController < ActionController::Base

    def index
        @author = Author.all  
    end


    def show
        @author = Author.find(params[:id])
    end

    def new
        @author = Author.new
    end

    def create
        Author.create(params.require(:author).permit(:first_name, :last_name, :number_of_books, :author_birthdate))
    
        redirect_to authors_path
    end

    def edit
        @author = Author.find(params[:id])
    end

    def update
        @author = Author.find(params[:id])
        @author.update(params.require(:author).permit(:first_name, :last_name, :number_of_books, :author_birthdate))
    
        redirect_to @author
    end

    def destroy
        @author = Author.find(params[:id])
        @author.destroy
        # redirect_to authors_path
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/_form.html.erb
<%= form_for @author do |f| %>
    <div class="field">
        <%= f.label :first_name, "First Name" %>
        <%= f.text_field :first_name %>
    </div>


    <div class="field">
        <%= f.label :last_name, "Last Name" %>
        <%= f.text_field :last_name %>
    </div>

    <div class="field">
        <%= f.label :number_of_books, "Number of Books" %>
        <%= f.text_field :number_of_books %>
    </div>

    <div class="field">
        <%= f.label :author_birthdate, "Date of Birth" %>
        <%= f.text_field :author_birthdate %>
    </div>

    <%= f.submit "Submit", :class => 'button' %>
<% end %>

app/views/authors/edit.html.erb
<h1>Edit <%= @author.first_name %></h1>

<%= render "form" %>

app/views/authors/index.html.erb
<% @author.each do |author| %>
<h1> <%= link_to "#{author.first_name}  #{author.last_name}", author_path(author)%> </h1>
<h3> <%= link_to "Edit Author", edit_author_path(author)%>
&nbsp;|&nbsp;
 <%= button_to "Delete Author", author_path(author),
            data: {turbo_method: :delete,
                   turbo_confirm: "are you sure??"} %></h3>
<% end %>

app/views/authors/new.html.erb
<h1>Create A New Author</h1>

<%= render "form" %>

app/views/authors/show.html.erb
<h1>Author Page</h1>

<h1> <%= "#{@author.first_name}  #{@author.last_name}" %> </h1>
<h1><%= @author.number_of_books%></h1>
<h1><%= @author.author_birthdate %></h1>
<h3> <%= link_to "Back to List of Authors?", authors_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeworkRuby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>